### ISSUE TITLE
Missing EFO disease subclass relations

### ISSUE THREAD

**Issue by cbizon** [INCATools/ubergraph#21]
I'm trying to do a query to get all the EFO diseases but I'm missing some things.  For instance, I'm not picking up EFO:0000275 (Atrial Fibrillation)

https://api.triplydb.com/s/_fEe_BEHd

It seems to know that AF is a subclass of cardiovascular disease, but not of disease.   The only thing I can see is that 'disease by anatomical system' and 'disorder by anatomical system' are mondo terms, but should that matter?

**Comment by matentzn** [comment]
Not my project but since I am lurking here :D

This could be because your query does not catch indirect subsumptions. Check for example this:
https://api.triplydb.com/s/vY0EnLkHA

In particular the `+` operator. 

Also, if you use FROM on any triplestore, you should be sure that the entire set of triples necessary for such queries of the transitive closure are present.

**Comment by balhoff** [comment]
This is an issue with the base file provided by EBI. It doesn't include all axioms needed to reconstitute the hierarchy they publish in the main file (it's missing some subClassOf axioms they inject for certain MONDO classes).

**Comment by matentzn** [comment]
@balhoff can you make an issue on the EFO repo? Not quite following what the right axiomatisation of base would be in the case of EFO.

**Comment by balhoff** [comment]
Closing this due to various logical issues with combining EFO with the other ontologies (#62).
