### ISSUE TITLE
consider creating a graph for assertions from each source ontology

### ISSUE THREAD

**Issue by balhoff** [INCATools/ubergraph#6]
Requested by @matentzn

**Comment by matentzn** [comment]
awesome! Thanks for considering it!

**Comment by TomConlin** [comment]
note for dippers output,
a minor variant of name graphs has existed since before the last relay
in the  experimental directory of the archive site. 

I will likely have a 2020 December candidate available  next week.
the most recent at the moment is
https://archive.monarchinitiative.org/202011/experimental/

**Comment by matentzn** [comment]
sheeding a tear of joy
